subreddits:
  - dating
  - relationships
  - relationship_advice
  - socialskills
  - OnlineDating
  - dating_advice

database:
  dbname: your_database_name
  user: your_database_user
  password: your_secure_database_password
  host: your-database-host.com
  port: 5432

gemini_api_key: "your_gemini_api_key_here" # Get from Google AI Studio

reddit_api:
  client_id: your_reddit_client_id
  client_secret: your_reddit_client_secret
  user_agent: "your_app_name:v1.0 (by /u/YourUsername)"

email:
  smtp_server: smtp.gmail.com              # Gmail's outgoing mail server
  smtp_port: 587                           # Use 587 for TLS (recommended)
  sender_email: your_email@gmail.com       # Your Gmail address
  sender_password: your_gmail_app_password # 16-character App Password from Google
  recipient_email: recipient@gmail.com

google_sheets:
  credentials_file: google_credentials.json  # Path to service account JSON file
  spreadsheet_name: Your_Spreadsheet_Name   # Name of the Google Sheets spreadsheet
  worksheet_name: Main                       # Name of the worksheet/tab 